chore: added delete command to config

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -21,44 +21,44 @@ commands:
           The name of project associated with the pipeline.
     steps:
       - run:
-        name: Deleting << parameters.schedule-name >>
-        command: |
-          if echo  "${CIRCLE_BUILD_URL}" | grep -E "GitHub|gh" > /dev/null; then
-            VCS="gh"
-          elif echo  "${CIRCLE_BUILD_URL}" | grep -E "BitBucket|bb" > /dev/null; then
-            VCS="bb"
-          else
-            VCS="circleci"
-          fi
-          URL="https://circleci.com/api/v2/project/${VCS}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/schedule"
-          curl -s --request GET \
-            --url "${URL}" \
-            --header "Circle-Token: $CIRCLE_TOKEN" > existing_schedules.json
+          name: Deleting << parameters.schedule-name >>
+          command: |
+            if echo  "${CIRCLE_BUILD_URL}" | grep -E "GitHub|gh" > /dev/null; then
+              VCS="gh"
+            elif echo  "${CIRCLE_BUILD_URL}" | grep -E "BitBucket|bb" > /dev/null; then
+              VCS="bb"
+            else
+              VCS="circleci"
+            fi
+            URL="https://circleci.com/api/v2/project/${VCS}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/schedule"
+            curl -s --request GET \
+              --url "${URL}" \
+              --header "Circle-Token: $CIRCLE_TOKEN" > existing_schedules.json
 
-          if jq '.' -c existing_schedules.json | grep "Project not found" > /dev/null; then
-            echo "The specified project is not found. Please check the project name vcs type or namespace."
-            exit 1
-          fi
+            if jq '.' -c existing_schedules.json | grep "Project not found" > /dev/null; then
+              echo "The specified project is not found. Please check the project name vcs type or namespace."
+              exit 1
+            fi
 
-          if jq ".items[] | .name" existing_schedules.json | grep "<< parameters.schedule-name >>" > /dev/null; then
-            SCHEDULE_ID=$(jq -r '.items[] | select( .name == '"\"<< parameters.schedule-name >>""') | .id' existing_schedules.json)
-            
-            set -x
-            curl -s --request DELETE \
-                --url https://circleci.com/api/v2/schedule/"${SCHEDULE_ID}" \
-                --header "Circle-Token: ${CIRCLE_TOKEN}" > status.json
-            set +x 
+            if jq ".items[] | .name" existing_schedules.json | grep "<< parameters.schedule-name >>" > /dev/null; then
+              SCHEDULE_ID=$(jq -r '.items[] | select( .name == '"\"<< parameters.schedule-name >>""') | .id' existing_schedules.json)
+              
+              set -x
+              curl -s --request DELETE \
+                  --url https://circleci.com/api/v2/schedule/"${SCHEDULE_ID}" \
+                  --header "Circle-Token: ${CIRCLE_TOKEN}" > status.json
+              set +x 
 
-            jq '.' status.json
-          else
-            echo "\"${ORB_EVAL_SCHEDULE_NAME}\" is not found. Please choose a valid schedule."
-          fi
+              jq '.' status.json
+            else
+              echo "\"${ORB_EVAL_SCHEDULE_NAME}\" is not found. Please choose a valid schedule."
+            fi
 
-          curl -s --request GET \
-            --url "${URL}" \
-            --header "Circle-Token: $CIRCLE_TOKEN" > current_schedules.json
+            curl -s --request GET \
+              --url "${URL}" \
+              --header "Circle-Token: $CIRCLE_TOKEN" > current_schedules.json
 
-          jq '.' current_schedules.json  
+            jq '.' current_schedules.json  
 
 workflows:
   test-deploy:
